### PR TITLE
Added Proper Toolbar

### LINKED ISSUE #83: Add toolbar in View Friends
Currently, toolbar is present in view friends xml file, but is not added in Java code due to which its a toolbar without user image and npChat as text.

### PR DESCRIPTION
**Pull request by somenath1435**
fixes #83 
Before:-
Screenshot_20190317-011107
After:-
Screenshot_20190317-010811

### CODE REVIEW

**Comment by somenath1435** [comment]
@jrandallclark please review

**Comment by somenath1435** [comment]
@jrandallclark please review

**Comment by somenath1435** [comment]
@jrandallclark resolved conflicts

**Comment by jrandallclark** [comment]
@somenath1435 Please fix the conflicts and I will merge this.

**Comment by somenath1435** [comment]
@jrandallclark resolved conflicts

**Pull request merged**
