### PR TITLE
Login Page UI is Improved

### PR DESCRIPTION
**Pull request by ayush4190**
Improved Login Page UI with a New Colour Scheme

### CODE REVIEW

**Comment by agawande** [comment]
So this needs to reference issue #4 right? Also please post some before and after screenshots.

**Comment by ayush4190** [comment]
old_login
new_login

This is the new layout . I am working on a dedicated sign up page for the app .

**Comment by ayush4190** [comment]
Hi
I had my Cultural Fest going on so I wasn't able to reply yesterday . I
have posted the screenshot of the new as well as the old login page , also I will like to work on a dedicated sign up page and changing
the layout of the main dashboard.

**Comment by jrandallclark** [comment]
While minor UI fixes are welcome, we are not set on how the final app will look, so major changes will not be accepted until we commit to a major overhaul to the design.

**Pull request closed without merging**
