### PR TITLE
psync: bump versions for ndn-cxx, boost; update README

### PR DESCRIPTION
**Pull request by agawande**
**Description (required)**

* Using latest ndn-cxx and boost version from crew
* Disabled treating warnings as errors in JNI build as PSync is a bit behind in crew
* Update build instructions in README

**Tests performed (required)**

Tested on Nexus 6 Android 7.1.1 emulator with API level 25.

### CODE REVIEW

**Comment by agawande** [comment]
To test this you will have to remove the existing psync install from ndk-build/packages/psync/
And update the crew folder.

**Comment by agawande** [comment]
@dev-ritik @jrandallclark Need this change in crew first and then install libsqlitejdbc through crew:
https://github.com/named-data-mobile/android-crew-staging/pull/3
CREW_OWNER=named-data-mobile crew.dir/crew install target/libsqlitejdbc

After that try to pull this change and see if it works. This should also solve the crash in x86 emulator and we can test through emulator now.

**Comment by cawka** [comment]
This patch is needed, at least on my system.  This would also requite updates of crew packages (I will try to upload them later today)
```patch
From 0afd0b9a11689aef211865494113fdf4211861c1 Mon Sep 17 00:00:00 2001
From: Alexander Afanasyev <aa@cs.fiu.edu>
Date: Tue, 18 Jun 2019 11:30:35 +0200
Subject: [PATCH] jni: Make sure build works on case-insensitive file systems
 (e.g., macOS)

This commit also corrects version of pre-compiled libsqlitejdbc and
ensures that x64_64 version of .apk is properly created.
---
 app/build.gradle                                        | 2 +-
 app/src/main/cpp/CMakeLists.txt                         | 4 ++--
 psync/build.gradle                                      | 2 +-
 psync/src/main/cpp/CMakeLists.txt                       | 8 ++++----
 psync/src/main/java/net/named_data/jni/psync/PSync.java | 2 +-
 5 files changed, 9 insertions(+), 9 deletions(-)

diff --git a/app/build.gradle b/app/build.gradle
index 1fdd1c3..ef64028 100644
--- a/app/build.gradle
+++ b/app/build.gradle
@@ -29,7 +29,7 @@ android {
             abi {
                 enable true // enable ABI split feature to create one APK per ABI
                 reset()
-                include "armeabi-v7a", "arm64-v8a", "x86"
+                include "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
                 universalApk false // don't generate an additional APK that targets all the ABIs
             }
         }
diff --git a/app/src/main/cpp/CMakeLists.txt b/app/src/main/cpp/CMakeLists.txt
index e25aafb..4279aab 100644
--- a/app/src/main/cpp/CMakeLists.txt
+++ b/app/src/main/cpp/CMakeLists.txt
@@ -2,8 +2,8 @@ cmake_minimum_required(VERSION 3.4.1)
 
 set(CMAKE_VERBOSE_MAKEFILE ON)
 
-set(SQLITE_JDBC_VERSION 3.25.2.1)
+set(SQLITE_JDBC_VERSION 3.25.2)
 set(SQLITE_JDBC_LIBS ${ANDROID_NDK}/packages/libsqlitejdbc/${SQLITE_JDBC_VERSION}/libs/${ANDROID_ABI})
 
 file(COPY ${SQLITE_JDBC_LIBS}/libsqlitejdbc.so
-        DESTINATION ${CMAKE_CURRENT_SOURCE_DIR}/../jniLibs/${ANDROID_ABI}/)
\ No newline at end of file
+       DESTINATION ${CMAKE_CURRENT_SOURCE_DIR}/../jniLibs/${ANDROID_ABI}/)
diff --git a/psync/build.gradle b/psync/build.gradle
index a48ecea..76bfcd7 100644
--- a/psync/build.gradle
+++ b/psync/build.gradle
@@ -17,7 +17,7 @@ android {
         ndk {
             // Specifies the ABI configurations of your native
             // libraries Gradle should build and package with your APK.
-            abiFilters 'x86', 'armeabi-v7a', 'arm64-v8a'
+            abiFilters 'x86', 'armeabi-v7a', 'arm64-v8a', "x86_64"
         }
     }
     buildTypes {
diff --git a/psync/src/main/cpp/CMakeLists.txt b/psync/src/main/cpp/CMakeLists.txt
index 0bd0fb0..47aacdc 100644
--- a/psync/src/main/cpp/CMakeLists.txt
+++ b/psync/src/main/cpp/CMakeLists.txt
@@ -47,10 +47,10 @@ add_library(libsql SHARED IMPORTED)
 set_target_properties(libsql PROPERTIES IMPORTED_LOCATION ${SQLITE_LIBS}/libsqlite3.so)
 
 # Add JNI
-add_library(psync SHARED psync-wrapper.cpp)
-target_include_directories(psync PUBLIC ${NDN_CXX_INCLUDE} ${Boost_INCLUDE_DIR} ${PSYNC_INCLUDE})
+add_library(psync-jni SHARED psync-wrapper.cpp)
+target_include_directories(psync-jni PUBLIC ${NDN_CXX_INCLUDE} ${Boost_INCLUDE_DIR} ${PSYNC_INCLUDE})
 
-target_link_libraries(psync libndn-cxx ${Boost_LIBRARIES} libsql libcrypto libssl android log libPSync)
+target_link_libraries(psync-jni libndn-cxx ${Boost_LIBRARIES} libsql libcrypto libssl android log libPSync)
 
 #-----------------------------------------------------------------------------------------------
 # Copy library files to src/main/lib so that gradle can pick them up to package in the apk
@@ -71,4 +71,4 @@ foreach( file_i ${Boost_COMPONENT_LIST})
 endforeach( file_i )
 
 file(COPY ${NDN_CXX_LIBS}/libndn-cxx.so DESTINATION ${LIBS_DIR})
-file(COPY ${PSYNC_LIBS}/libPSync.so DESTINATION ${LIBS_DIR})
\ No newline at end of file
+file(COPY ${PSYNC_LIBS}/libPSync.so DESTINATION ${LIBS_DIR})
diff --git a/psync/src/main/java/net/named_data/jni/psync/PSync.java b/psync/src/main/java/net/named_data/jni/psync/PSync.java
index 59dbe05..87b7b03 100644
--- a/psync/src/main/java/net/named_data/jni/psync/PSync.java
+++ b/psync/src/main/java/net/named_data/jni/psync/PSync.java
@@ -7,7 +7,7 @@ public class PSync {
     private static PSync s_psync;
 
     static {
-        System.loadLibrary("psync");
+        System.loadLibrary("psync-jni");
     }
 
     public interface OnSyncDataCallBack {
-- 
2.22.0

```

**Comment by cawka** [comment]
crew (binary) packages uploaded and shasums updated

**Comment by cawka** [comment]
Btw. The app didn't crash on me when I compiled it. Is there a specific place where not having nativeDB of sqlitejdbc should have triggered the error?

**Comment by agawande** [comment]
Since this app uses AndroidSqlite3Pib I though it must use that indirectly somehow.
In your test application are you trying to instantiate NativeDB directly?
jNDN uses sqlite-jdbc (3.23.1) for Android (https://github.com/named-data/jndn/blob/40ff5f50b682df51c28c3c4ae51158f9b46ce937/pom-android.xml#L37) and does not seem to use the class directly.

**Comment by cawka** [comment]
I was using this photo app for my tests.

Ehm. Are you saying all this business with sqlitejdbc is just for jndn? jndn-android and AndroidSqlite3Pib is not relying on jdbc... It works using android sqlite routines...

**Comment by agawande** [comment]
Then why does it have it as a dependency in pom-android? It should be removed?

**Comment by agawande** [comment]
Doesn't this use it: https://github.com/named-data/jndn/blob/e656e455517253a97b0173e4c2882d73596f31eb/src/net/named_data/jndn/security/pib/PibSqlite3.java#L103?

**Comment by cawka** [comment]
Huh. We wasted everybody time then. You can ignore that dependency (no clue why is it in pom, could be limitation of build system, you can ask Jeff). That’s why there is AndroidSqlitePib, which suppose to work without issues on android and without requiring anything from JNI.

**Comment by jrandallclark** [comment]
I don't understand why I'm still having trouble installing the PSync JNI. The command `CREW_OWNER=named-data-mobile crew.dir/crew install target/sqlite target/openssl` tries to install some dependencies, but can't connect to the server:
 ```
CREW_OWNER=named-data-mobile crew.dir/crew install target/sqlite target/openssl
Warning: using system ruby
warning: target/sqlite:3.18.0_1 already installed

calculating dependencies for target/openssl: 
  dependencies to install: 
downloading https://crew.crystax.net:9876/packages/openssl-1.0.2m_1.tar.xz
error: failed to download https://crew.crystax.net:9876/packages/openssl-1.0.2m_1.tar.xz: code: 7; text: failed to connect to host

```

**Comment by agawande** [comment]
Thanks for the help, @cawka 
If nothing else I learned a bit more about crew :le_hand:

**Pull request merged**
