### PR TITLE
Add issue template and pull request template

### PR DESCRIPTION
**Pull request by prajurock**

### CODE REVIEW

**Comment by prajurock** [comment]
@jrandallclark please review.

**Comment by agawande** [comment]
Looks good to me, is this inspired/taken from somewhere?

**Review by agawande — COMMENTED** [review]
Should these go under a new docs folder? Not sure what is the usual way for android repos.

**Comment by prajurock** [comment]
> Should these go under a new docs folder? Not sure what is the usual way for android repos.
No. Just like this I saw in some project.

**Comment by prajurock** [comment]
> @jrandallclark please review.

yes It is inspired by one app but with some changes.

**Pull request merged**
