### PR TITLE
Added Location services. Make sure that Location is turned On.

### PR DESCRIPTION
**Pull request by deepakpsad**
I have added the location services using LiveData<Location>. 
To successfully retrieve the location, please make sure that the location is turned On on your device.

Issues Remaining:

1. Clubbing all the permission request into a single request. Right now we need to restart the app to get to the location permission.
2. Add a GPS On/Off check.

### CODE REVIEW

**Comment by somenath1435** [comment]
@deepak140596 there are many extra space in the code.Try to reduce it.

**Comment by zedlabs** [comment]
@deepak140596 hi, can you tell me why you have implemented location services, as far as i know the app doesn't provide any feature which would have required it.

**Comment by deepakpsad** [comment]
@zedlabs As per the instructions, these are the primary deliverables

Deliverables:
--
Primary:Implement prefix propagation to announce the app on NDN testbed
Implement a way to share list of friends in a decentralized way using PSync
Enhance friend functionality to create friends remotely
**Implement a GPS location feed to gather public content by locality**
Release app on Google Play Store

To gather public content locally, we need to save location for each post and also need location to get local content.

**Comment by deepakpsad** [comment]
@somenath1435 
Thanks for the feedback. I will reduce the blank spaces right away.

**Comment by jrandallclark** [comment]
What are the benefits of using Kotlin over Java for this?

**Comment by deepakpsad** [comment]
Honestly, none!
The only benefit here would be code readability.

**Comment by jrandallclark** [comment]
I think we would rather keep the project Java-only for the time being.

**Pull request closed without merging**
