### PR TITLE
Implemented RecyclerView for ViewFriends and SelectRecipients and NewContentActivity.

### PR DESCRIPTION
**Pull request by ashwinyogesh**
ViewFriends->OnClick Displays a toast with FriendName. Can be used to link to diffrent page in Future.
SelectRecipients-> Multi-select RecyclerView. The send button becomes visible when atleast one friend is selected.

### CODE REVIEW

**Review by jrandallclark — CHANGES_REQUESTED** [review]
Did you test sending and receiving photos? The RecyclerView works fine for viewing friends and selecting recipients, but trying to view received photos causes and error and the photos never appear in the list.

Error:
E/RecyclerView: No adapter attached; skipping layout
E/RecyclerView: No adapter attached; skipping layout

**Comment by ashwinyogesh** [comment]
I will work on it and submit PR by EOD.

**Comment by ashwinyogesh** [comment]
Hey @jrandallclark I have implemented RecyclerView in NewContentActivity as well, this addresses the  
`Error:
E/RecyclerView: No adapter attached; skipping layout`
Have a look at it and let me know if there are any more changes required.

**Review by jrandallclark — CHANGES_REQUESTED** [review]
Could you remove the extra toast messages you added?
- Having a toast message with 'Friend name: mw' is fine when clicking on a friend's name in View Friends, but I don't like the 'Count: 0' part.
- The 'Path of chosen file' message is uncessary
- The toast message with the file location when trying to view a received file is unnecessary and distracting.

Additionally, clicking 'See Photos' when your photo list is empty still causes the "E/RecyclerView: No adapter attached; skipping layout" error to appear in the logs. The app still works without issue, but this should be fixed.

**Comment by somenath1435** [comment]
@AshwinChandlapur squash commits

**Review by jrandallclark — APPROVED** [review]

**Pull request merged**
