### PR TITLE
1.Check for NFD app at the startup 2. RecyclerView for ViewFriendsActivity and SelectRecipientsActivity 3. Positive & Negative Buttons for alertDialog in requestCode = FILE_SELECT_REQUEST_CODE.

### PR DESCRIPTION
**Pull request by ashwinyogesh**
Check if NDN Forwarding Daemon is installed.
If installed -> Continue Regular Onboarding
If not installed -> Show a Toast Message and request User to install NDN

### CODE REVIEW

**Comment by ashwinyogesh** [comment]
This commit adds recyclerView to load friendsList in ViewFriendsActivity and SelectRecipientsActivity. 

In ViewFriendsActivity, All friends are displayed in recyclerView. If no friend exist, then a toast message "You haven't added any friends" is displayed. As of now, onClick of FriendName a Toast is displayed which can be further extended to ideas like linking to a different page where user will be able to view Friend's profile or remove him/her from FriendsList. 

In SelectRecipientsActivity, multi-select OnClick is implemented, user can select multiple friends and share the photo with them. If no friend is selected, the SEND button is not visible. For it to be visible, user should select at-least one friend. If no friend exist, then a toast message "You haven't added any friends" is displayed.

**Comment by somenath1435** [comment]
@AshwinChandlapur squash the commits

**Comment by ashwinyogesh** [comment]
Hi @jrandallclark , I have added one more commit for the issue #124. The code adds 2 buttons for the alertDialog.
Positive-> ShareFiles->OnClick-> Passes the path of selectedFile to SelectRecipientsActivity
Negative-> Cancel-> Dismisses Alert Dialog

Tested on Moto-g6 Play.

**Comment by jrandallclark** [comment]
@AshwinChandlapur Why did you close this?

**Comment by ashwinyogesh** [comment]
I opened Individual Pull Request for each task. I felt submitting all tasks in a single PR would make things clumsy.

**Pull request closed without merging**
