### PR TITLE
fix: Scan QR page

### LINKED ISSUE #45: Add some text in Display QR page
Some text like "Scan QR Code" should be added.

### PR DESCRIPTION
**Pull request by somenath1435**
fixes #45 
Changes:
Before:-
whatsapp image 2019-03-06 at 6 23 25 am
After:-
whatsapp image 2019-03-06 at 6 23 25 am 1

### CODE REVIEW

**Comment by somenath1435** [comment]
@jrandallclark please review this PR

**Comment by jrandallclark** [comment]
I'm not sure I see the purpose of adding this.

**Comment by somenath1435** [comment]
@jrandallclark actually user should be told to scan the QR code.
Just displaying QR code may not be meaningful. 
Adding the text is necessary.

**Comment by jrandallclark** [comment]
Sorry. I just don't like the way it looks.

**Pull request closed without merging**
