### PR TITLE
Picture selection

### PR DESCRIPTION
**Pull request by dev-ritik**
Add a received file browser.

It enlists all the files in the `m_rcvdFilesDir` and `m_rcvdPhotosDir` in the order they were last modified. On clicking each item, it opens them via other respective apps. 
An image is added below.
Screenshot_20190726-141718

### CODE REVIEW

**Review by jrandallclark — CHANGES_REQUESTED** [review]
The consumer crashes upon trying to view a photo sent by the "Share Pictures" button when it tries to check for the existence of location data on line 97 of ViewPhotosFragment.

**Comment by jrandallclark** [comment]
Pictures shared with "Share pictures" shouldn't appear under the "See Photos" part of the app.

**Comment by jrandallclark** [comment]
Similarly, pictures taken with "Camera" in the app shouldn't appear under "browse rcvd."

**Comment by dev-ritik** [comment]
@jrandallclark PTAL.

**Comment by jrandallclark** [comment]
One problem that we need to consider is what happens when a user tries to share the same file more than once. Right now we use the filename as the unique key in the file info, but we'll need to use something else. If you share the same file a second time, the database throws an exception. One idea I've considered is adding a timestamp to the interest name and file info. 

@agawande @dev-ritik Do you have any ideas?

**Comment by jrandallclark** [comment]
@dev-ritik Dr. Wang came up with a simple solution. When we share a file, we should check for it in the database, if it exists, we should use the same symmetric key to encrypt it as we had before.

**Comment by dev-ritik** [comment]
Yup ok! I will change it accordingly.

**Pull request merged**
