### PR TITLE
added test for nullability of image recieved 

### LINKED ISSUE #85: App crash on sharing image through camera
android version: android 6.0.1
api : 23

app crashes due to inability to decode the bitmap captured, i am working on it

### PR DESCRIPTION
**Pull request by zedlabs**
fixes #85 

fixes the bug mentioned above 
clicking on the avatar on the toolbar opens the settings activity

### CODE REVIEW

**Comment by somenath1435** [comment]
@zedlabs squash commits

**Comment by agawande** [comment]
@jrandallclark can you test and merge this?

**Review by jrandallclark — CHANGES_REQUESTED** [review]
```                
Bitmap bitmap = BitmapFactory.decodeFile(m_curr_photo_file.getAbsolutePath())
out = new FileOutputStream(m_curr_photo_file);
```
These need to be switched around like the original code or it causes the app to save a null image.

**Comment by zedlabs** [comment]
can i close this and create a different pr as i have deleted this branch (i had to refork because of some problem).

**Comment by jrandallclark** [comment]
Yes. That's fine.

**Comment by zedlabs** [comment]
#139 is the required change

**Pull request closed without merging**
